# Generated by Django 2.2.4 on 2019-08-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=225)),
                ('major', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
