# Generated by Django 2.1.8 on 2020-11-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190808_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('area', models.TextField(max_length=10)),
                ('connect', models.TextField(max_length=10)),
            ],
        ),
    ]
